/**
 * Barcode regression — spec §8: photos with known SKUs, asserted end to end.
 *
 * The fixtures are generated by tools/make_fixtures.py: a Code 128 label on a
 * textured scene, at normal contrast, at contrast low enough to force the
 * 2.5x retry, and rotated 90 degrees. label-wrapped-0000705.jpg is a real
 * production photo (downscaled to the 1600px the scanner reads): a speckled
 * print under shrink-wrap that the single-line scanner missed.
 */

import { describe, it, expect, loadFixture } from './runner.js';
import { detectSku, isValidSku, toGreyscale, boostContrast, downscaleForScan, ocrRegion, cropForOcr } from '../core/barcode.js';
import { scanCode128 } from '../core/code128.js';

const SKU = '0000646';

describe('SKU validity (§2.2)', () => {
  it('accepts exactly 7 digits', () => {
    expect(isValidSku('0000646')).toBeTruthy();
    expect(isValidSku('1234567')).toBeTruthy();
  });

  it('rejects anything else', () => {
    for (const bad of ['123456', '12345678', 'A123456', '123 456', '', null, undefined, 1234567]) {
      expect(isValidSku(bad)).toBeFalsy(`accepted ${JSON.stringify(bad)}`);
    }
  });
});

describe('Barcode preprocessing (§2.2)', () => {
  it('downscales a 24MP frame to a longest side of ~1600px', () => {
    // The real input: 6000x4000. Scanning the downscaled copy is 3-4x faster
    // and sufficient, because the label is shot deliberately at close range.
    const full = new OffscreenCanvas(6000, 4000);
    const { width, height } = downscaleForScan(full, 1600);
    expect(Math.max(width, height)).toBe(1600, 'longest side');
    expect(height).toBe(1067, 'aspect ratio preserved');
  });

  it('never upscales an image already smaller than the target', async () => {
    // The fixtures are 1400x1000 and 300x200; both must pass through untouched.
    const label = await loadFixture(`label-${SKU}.png`);
    expect(downscaleForScan(label, 1600).width).toBe(label.width);
    label.close();

    const wm = await loadFixture('watermark-small.png');
    expect(downscaleForScan(wm, 1600).width).toBe(300);
    wm.close();
  });

  it('boosts contrast about mid-grey by 2.5x', () => {
    const grey = Uint8Array.from([0, 100, 118, 128, 138, 150, 255]);
    const boosted = boostContrast(grey, 2.5);
    expect(boosted[3]).toBe(128, 'mid-grey is the pivot');
    expect(boosted[2]).toBe(103, '(118-128)*2.5+128');
    expect(boosted[4]).toBe(153, '(138-128)*2.5+128');
    expect(boosted[0]).toBe(0, 'clamped');
    expect(boosted[6]).toBe(255, 'clamped');
  });

  it('converts RGBA to BT.601 luma', () => {
    const rgba = Uint8ClampedArray.from([255, 255, 255, 255, 0, 0, 0, 255, 255, 0, 0, 255]);
    const grey = toGreyscale(rgba);
    expect(grey[0]).toBe(255);
    expect(grey[1]).toBe(0);
    expect(grey[2]).toBe(76, '0.299 * 255');
  });
});

describe('Barcode end to end (§8 regression)', () => {
  it('reads the SKU from a normal-contrast label', async () => {
    const label = await loadFixture(`label-${SKU}.png`);
    const result = await detectSku(label);
    label.close();
    expect(result.sku).toBe(SKU);
    expect(result.boosted).toBeFalsy('a clean label must not need the retry');
  });

  it('reads a label rotated 90 degrees', async () => {
    const label = await loadFixture(`label-rotated-${SKU}.png`);
    const result = await detectSku(label);
    label.close();
    expect(result.sku).toBe(SKU);
  });

  it('recovers a low-contrast label via the 2.5x retry', async () => {
    // Bars at 120/255 on a 150/255 card: below the scanner's contrast floor,
    // so pass 1 must fail and the boost must rescue it.
    const label = await loadFixture(`label-lowcontrast-${SKU}.png`);
    const result = await detectSku(label);
    label.close();
    expect(result.sku).toBe(SKU);
  });

  it('returns null for a photo with no label — most photos do', async () => {
    const base = await loadFixture('base.png');
    const result = await detectSku(base);
    base.close();
    expect(result.sku).toBeNull();
  });

  it('stays well inside a 1s-per-photo budget on the downscaled copy', async () => {
    const label = await loadFixture(`label-${SKU}.png`);
    const result = await detectSku(label);
    label.close();
    expect(result.ms < 2000).toBeTruthy(`took ${result.ms}ms`);
  });
});

describe('Real label under shrink-wrap (production regression)', () => {
  it('reads SKU 0000705 through toner speckle and film glare', async () => {
    const photo = await loadFixture('label-wrapped-0000705.jpg');
    const result = await detectSku(photo);
    photo.close();
    expect(result.sku).toBe('0000705');
  });

  it('reads SKU 0000706 (false stop-pattern match, see code128.test.js)', async () => {
    const photo = await loadFixture('label-wrapped-0000706.jpg');
    const result = await detectSku(photo);
    photo.close();
    expect(result.sku).toBe('0000706');
  });

  it('is only readable because scan lines are band-averaged', async () => {
    // Documents the cause: one-pixel scan lines decode on a single row here,
    // which the default 6-row stride steps straight over.
    const photo = await loadFixture('label-wrapped-0000705.jpg');
    const { canvas, width, height } = downscaleForScan(photo, 1600);
    photo.close();
    const grey = toGreyscale(canvas.getContext('2d').getImageData(0, 0, width, height).data);
    const valid = (t) => isValidSku(t);
    expect(scanCode128(grey, width, height, { band: 1, validate: valid })?.text === '0000705').toBeFalsy('single lines read it');
    expect(scanCode128(grey, width, height, { validate: valid })?.text).toBe('0000705');
  });
});

describe('OCR fallback — where to crop', () => {
  const best = (o) => ({ orientation: 'row', index: 500, x0: 400, x1: 600, symbols: 4, reverse: false, ...o });

  it('ignores a partial read too short to be a label', () => {
    expect(ocrRegion(best({ symbols: 2 }), 1600, 1067)).toBeNull();
    expect(ocrRegion(null, 1600, 1067)).toBeNull();
  });

  it('covers the whole estimated barcode and the digits under it', () => {
    // 4 symbols over 200px -> ~415px for a full 7-digit code.
    const r = ocrRegion(best(), 1600, 1067);
    expect(r.x < 400).toBeTruthy('starts before the first bar');
    expect(r.x + r.w > 400 + 415).toBeTruthy('reaches past the estimated end');
    expect(r.y < 500 && r.y + r.h > 500 + 150).toBeTruthy('extends below the scan line to the digits');
    expect(r.rotate).toBe(0);
  });

  it('turns upside-down and sideways labels upright', () => {
    expect(ocrRegion(best({ reverse: true }), 1600, 1067).rotate).toBe(180);
    expect(ocrRegion(best({ orientation: 'column' }), 1600, 1067).rotate).toBe(270);
    expect(ocrRegion(best({ orientation: 'column', reverse: true }), 1600, 1067).rotate).toBe(90);
  });

  it('stays inside the image', () => {
    const r = ocrRegion(best({ x0: 1500, x1: 1590, index: 1050 }), 1600, 1067);
    expect(r.x >= 0 && r.y >= 0 && r.x + r.w <= 1600 && r.y + r.h <= 1067).toBeTruthy();
  });
});

/** The real 0000706 label with a white stripe painted through the bars. */
async function damagedLabel() {
  const photo = await loadFixture('label-wrapped-0000706.jpg');
  const canvas = new OffscreenCanvas(photo.width, photo.height);
  const ctx = canvas.getContext('2d');
  ctx.drawImage(photo, 0, 0);
  photo.close();
  ctx.fillStyle = '#e8e8ec';
  ctx.fillRect(790, 380, 26, 270); // through the middle of the bars, clear of the digits
  return canvas;
}

describe('OCR fallback — a label whose barcode is damaged', () => {
  it('fails to decode but flags the photo as a label to OCR', async () => {
    const result = await detectSku(await damagedLabel());
    expect(result.sku).toBeNull();
    expect(result.ocrRegion).toBeTruthy('no OCR region for a half-readable label');
  });

  it('does not flag an ordinary photo', async () => {
    const scene = await loadFixture('base.png');
    const result = await detectSku(scene);
    scene.close();
    expect(result.ocrRegion ?? null).toBeNull();
  });

  it('crops the printed digits, which serve.py reads as the SKU', async () => {
    const frame = await damagedLabel();
    const result = await detectSku(frame);
    const crop = cropForOcr(frame, result.ocrRegion, result.scanScale);
    expect(crop.width > 100 && crop.height > 100).toBeTruthy('crop too small');

    const config = await fetch('/backend/config').then((r) => (r.ok ? r.json() : null)).catch(() => null);
    if (!config?.ocr) return; // not served by serve.py with Tesseract — nothing more to check here
    // Both ways up, as the worker does: the read direction of a damaged
    // barcode is a guess, and the wrong way up reads as other digits.
    const { identify } = await import('../app/ocr.js');
    const blobs = [];
    for (const turn of [0, 180]) {
      const region = { ...result.ocrRegion, rotate: (result.ocrRegion.rotate + turn) % 360 };
      blobs.push(await cropForOcr(frame, region, result.scanScale).convertToBlob({ type: 'image/jpeg', quality: 0.92 }));
    }
    const read = await identify(blobs);
    expect(read?.candidates ?? []).toContain('0000706');
  });
});
